CREATE TABLE stage.stgmedicosematividade
(
  id BIGINT
, crm BIGINT
, datainscricaocrm TIMESTAMP
, tipodecrm BIGINT
, contagemdocrm BIGINT
, situacaodetalhada BIGINT
, situacaogeral BIGINT
, ufdeinscricao BIGINT
, municipio BIGINT
, estratomunicipio BIGINT
, classemunicipio BIGINT
, capitalinterior BIGINT
, regiaoinscricao BIGINT
, datanascimento TIMESTAMP
, idade TEXT
, idadecatum BIGINT
, idadecatdois BIGINT
, sexo TEXT
, sexodescricao TEXT
, municipiodenaturalidadedesc TEXT
, municipiodenaturalidade BIGINT
, ufdenaturalidade TEXT
, ufdenaturalidadedesc BIGINT
, regiaodenaturalidade BIGINT
, pais TEXT
, escola TEXT
, universidadeorigem BIGINT
, naturezajuridicaescolamedica BIGINT
, municipioescolamedicadesc TEXT
, municipioescolamedica BIGINT
, ufdaescolamedica BIGINT
, dataformatura TEXT
, tempodeformado BIGINT
, datasituacaodetalhada TEXT
, municipioresidencia BIGINT
, cepresidencia TEXT
, ufderesidencia BIGINT
, municipioresidenciadesc BIGINT
, municipiocomercialdesc TEXT
, cepmunicipiocomercial BIGINT
, ufcomercial TEXT
, municipiocomercial BIGINT
, municipiodecorrespondencia TEXT
, cepdecorrespondecia BIGINT
, ufdecorrespondecia TEXT
, programaresidenciaemcurso BIGINT
, primeiraresidencia BIGINT
, segundaresidencia BIGINT
, terceiraresidencia BIGINT
, quartaresidencia BIGINT
, especialidade BIGINT
, acupuntura BIGINT
, alergiaimunologia BIGINT
, anestesiologia BIGINT
, angiologia BIGINT
, cardiologia BIGINT
, cirurgiacardiovascular BIGINT
, cirurgiadamao BIGINT
, cirurgiadecabecaepescoco BIGINT
, cirurgiadoaparelhodigestivo BIGINT
, cirurgiageral BIGINT
, cirurgiaoncologica BIGINT
, cirurgiapediatrica BIGINT
, cirurgiaplastica BIGINT
, cirurgiatoracia BIGINT
, cirurgiavascular BIGINT
, clinicamédica BIGINT
, coloproctologia BIGINT
, dermatologia BIGINT
, endocrinologiaemetabologia BIGINT
, endoscopia BIGINT
, gastroenterologia BIGINT
, geneticamedica BIGINT
, geriatria BIGINT
, ginecologiaeobstetricia BIGINT
, hematologiaehemoterapia BIGINT
, homeopatia BIGINT
, infectologia BIGINT
, mastologia BIGINT
, medicinadeemergência BIGINT
, medicinadefamiliaecomunidade BIGINT
, medicinadotrabalho BIGINT
, medicinadetrafego BIGINT
, medicinaesportiva BIGINT
, medicinafisicaereabilitacao BIGINT
, medicinaintensiva BIGINT
, medicinalegalepericiamedica BIGINT
, medicinanuclear BIGINT
, medicinapreventivaesocial BIGINT
, nefrologia BIGINT
, neurocirurgia BIGINT
, neurologia BIGINT
, nutrologia BIGINT
, oftalmologia BIGINT
, oncologiaclinica BIGINT
, ortopediaetraumatologia BIGINT
, otorrinolaringologia BIGINT
, patologia BIGINT
, patologiaclinicamedicinalaboratorial BIGINT
, pediatria BIGINT
, pneumologia BIGINT
, psiquiatria BIGINT
, radiologiadiagnosticoporimagem BIGINT
, radioterapia BIGINT
, reumatologia BIGINT
, urologia BIGINT
, especialidadescirurgicas BIGINT
, sao BIGINT
, total_tit BIGINT
)
;