-- Criando Tabela de Medicos para armazenar dados do Arquivo CSV -- 
CREATE TABLE stage.medicosematividade
(
  id BIGINT
, crm BIGINT
, DataInscricaoCRM TIMESTAMP
, TipoDeCRM BIGINT
, ContagemDoCRm BIGINT
, SituacaoDetalhada BIGINT
, SituacaoGeral BIGINT
, UfDeInscricao BIGINT
, Municipio BIGINT
, EstratoMunicipio BIGINT
, ClasseMunicipio BIGINT
, CapitalInterior BIGINT
, RegiaoInscricao BIGINT
, DataNascimento TIMESTAMP
, Idade TEXT
, IdadeCatUm BIGINT
, IdadeCatDois BIGINT
, Sexo TEXT
, SexoDescricao TEXT
, MunicipioDeNaturalidadeDesc TEXT
, MunicipioDeNaturalidade BIGINT
, UfDeNaturalidade TEXT
, UfDeNaturalidadeDesc BIGINT
, RegiaoDeNaturalidade BIGINT
, Pais TEXT
, Escola TEXT
, UniversidadeOrigem BIGINT
, NaturezaJuridicaEscolaMedica BIGINT
, MunicipioEscolaMedicaDesc TEXT
, MunicipioEscolaMedica BIGINT
, UfDaEscolaMedica BIGINT
, DataFormatura TEXT
, TempoDeFormado BIGINT
, DataSituacaoDetalhada TEXT
, MunicipioResidencia BIGINT
, CEPResidencia TEXT
, UfDeResidencia BIGINT
, MunicipioResidenciaDesc BIGINT
, MunicipioComercialDesc TEXT
, CEPMunicipioComercial BIGINT
, UfComercial TEXT
, MunicipioComercial BIGINT
, MunicipioDeCorrespondencia TEXT
, CEPDeCorrespondecia BIGINT
, UfDeCorrespondecia TEXT
, ProgramaResidenciaEmCurso BIGINT
, PrimeiraResidencia BIGINT
, SegundaResidencia BIGINT
, TerceiraResidencia BIGINT
, QuartaResidencia BIGINT
, Especialidade BIGINT
, Acupuntura BIGINT
, AlergiaImunologia BIGINT
, Anestesiologia BIGINT
, Angiologia BIGINT
, Cardiologia BIGINT
, CirurgiaCardiovascular BIGINT
, CirurgiadaMao BIGINT
, CirurgiadeCabecaePescoco BIGINT
, CirurgiadoAparelhoDigestivo BIGINT
, CirurgiaGeral BIGINT
, CirurgiaOncologica BIGINT
, CirurgiaPediatrica BIGINT
, CirurgiaPlastica BIGINT
, CirurgiaToracia BIGINT
, CirurgiaVascular BIGINT
, ClinicaMédica BIGINT
, Coloproctologia BIGINT
, Dermatologia BIGINT
, EndocrinologiaeMetabologia BIGINT
, Endoscopia BIGINT
, Gastroenterologia BIGINT
, GeneticaMedica BIGINT
, Geriatria BIGINT
, GinecologiaeObstetricia BIGINT
, HematologiaeHemoterapia BIGINT
, Homeopatia BIGINT
, Infectologia BIGINT
, Mastologia BIGINT
, MedicinadeEmergência BIGINT
, MedicinaDeFamiliaeComunidade BIGINT
, MedicinaDoTrabalho BIGINT
, MedicinadeTrafego BIGINT
, MedicinaEsportiva BIGINT
, MedicinaFisicaeReabilitacao BIGINT
, MedicinaIntensiva BIGINT
, MedicinaLegalEPericiaMedica BIGINT
, MedicinaNuclear BIGINT
, MedicinaPreventivaESocial BIGINT
, Nefrologia BIGINT
, Neurocirurgia BIGINT
, Neurologia BIGINT
, Nutrologia BIGINT
, Oftalmologia BIGINT
, OncologiaClinica BIGINT
, OrtopediaETraumatologia BIGINT
, Otorrinolaringologia BIGINT
, Patologia BIGINT
, PatologiaClinicaMedicinaLaboratorial BIGINT
, Pediatria BIGINT
, Pneumologia BIGINT
, Psiquiatria BIGINT
, RadiologiaDiagnosticoPorImagem BIGINT
, Radioterapia BIGINT
, Reumatologia BIGINT
, Urologia BIGINT
, EspecialidadesCirurgicas BIGINT
, SAO BIGINT
, total_tit BIGINT);